### PR TITLE
Change attrs typing

### PR DESCRIPTION
**Pull request by loichuder**
See https://github.com/usnistgov/h5wasm/issues/19#issuecomment-1115795826

### CODE REVIEW

**Comment by bmaranville** [comment]
If this works for you, I'll merge.  What is the easiest way to test or find this error?  Neither the linter nor the typescript compiler complained about it the way it was.

**Comment by loichuder** [comment]
After a few experiments on the TS playground, it seems to me that using `Object.defineProperty` prevents Typescript to statically check the object.

I found some examples showing how to work around this but it is quite the journey (see https://fettblog.eu/typescript-assertion-signatures/).

I will try to work on a test demonstrating the issues I had with the previous type.

**Comment by loichuder** [comment]
> I will try to work on a test demonstrating the issues I had with the previous type.

Well I cannot do it in the end cause this is a TS issue and tests are in JS. Instead, here is a sandbox: https://codesandbox.io/s/h5wasm-attr-typing-fzwe4c?file=/src/App.tsx. 

Basically, it boils down to _attr is typed as {get(): Attribute, enumerate: true} while the actual object is Attribute_. As I said, because TS cannot statically check the `Object.defineProperty` part, the only valid typing for TS is the one given at declaration:
```
let attrs: {[key: string]: {get(): Attribute, enumerable: true}}  = {};
```

In fact, you could give any type as long as it agrees with the declared object `{}`... The static check could be restored by using something else than `Object.defineProperty`.

**Comment by bmaranville** [comment]
Thanks for checking into this!  It's possible making attrs lazy in this way is more harmful than helpful.

**Pull request merged**
