### PR TITLE
Mark optional parameters in `H5Module` interface

### PR DESCRIPTION
**Pull request by axelboc**

### CODE REVIEW

**Review by bmaranville — APPROVED** [review]
Looks good!  Thanks for catching this.

**Comment by bmaranville** [comment]
Do you want another release with these changes, or can it wait until some feature changes in the future?

**Comment by axelboc** [comment]
It can wait, no worries 😉 - sorry forgot to update the CHANGELOG

**Comment by axelboc** [comment]
Done 😊

**Pull request merged**
